package eu.europa.ec.webapi;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.9
 * 2017-01-17T10:57:01.168+01:00
 * Generated source version: 3.1.9
 * 
 */
@WebService(targetNamespace = "urn:ec.europa.eu:taxud:vies:services:checkVat", name = "checkVatPortType")
@XmlSeeAlso({ObjectFactory.class})
public interface CheckVatPortType {

    @WebMethod
    @RequestWrapper(localName = "checkVatApprox", targetNamespace = "urn:ec.europa.eu:taxud:vies:services:checkVat:types", className = "eu.europa.ec.webapi.CheckVatApprox")
    @ResponseWrapper(localName = "checkVatApproxResponse", targetNamespace = "urn:ec.europa.eu:taxud:vies:services:checkVat:types", className = "eu.europa.ec.webapi.CheckVatApproxResponse")
    public void checkVatApprox(
        @WebParam(mode = WebParam.Mode.INOUT, name = "countryCode", targetNamespace = "urn:ec.europa.eu:taxud:vies:services:checkVat:types")
        javax.xml.ws.Holder<java.lang.String> countryCode,
        @WebParam(mode = WebParam.Mode.INOUT, name = "vatNumber", targetNamespace = "urn:ec.europa.eu:taxud:vies:services:checkVat:types")
        javax.xml.ws.Holder<java.lang.String> vatNumber,
        @WebParam(mode = WebParam.Mode.INOUT, name = "traderName", targetNamespace = "urn:ec.europa.eu:taxud:vies:services:checkVat:types")
        javax.xml.ws.Holder<java.lang.String> traderName,
        @WebParam(mode = WebParam.Mode.INOUT, name = "traderCompanyType", targetNamespace = "urn:ec.europa.eu:taxud:vies:services:checkVat:types")
        javax.xml.ws.Holder<java.lang.String> traderCompanyType,
        @WebParam(mode = WebParam.Mode.INOUT, name = "traderStreet", targetNamespace = "urn:ec.europa.eu:taxud:vies:services:checkVat:types")
        javax.xml.ws.Holder<java.lang.String> traderStreet,
        @WebParam(mode = WebParam.Mode.INOUT, name = "traderPostcode", targetNamespace = "urn:ec.europa.eu:taxud:vies:services:checkVat:types")
        javax.xml.ws.Holder<java.lang.String> traderPostcode,
        @WebParam(mode = WebParam.Mode.INOUT, name = "traderCity", targetNamespace = "urn:ec.europa.eu:taxud:vies:services:checkVat:types")
        javax.xml.ws.Holder<java.lang.String> traderCity,
        @WebParam(name = "requesterCountryCode", targetNamespace = "urn:ec.europa.eu:taxud:vies:services:checkVat:types")
        java.lang.String requesterCountryCode,
        @WebParam(name = "requesterVatNumber", targetNamespace = "urn:ec.europa.eu:taxud:vies:services:checkVat:types")
        java.lang.String requesterVatNumber,
        @WebParam(mode = WebParam.Mode.OUT, name = "requestDate", targetNamespace = "urn:ec.europa.eu:taxud:vies:services:checkVat:types")
        javax.xml.ws.Holder<javax.xml.datatype.XMLGregorianCalendar> requestDate,
        @WebParam(mode = WebParam.Mode.OUT, name = "valid", targetNamespace = "urn:ec.europa.eu:taxud:vies:services:checkVat:types")
        javax.xml.ws.Holder<java.lang.Boolean> valid,
        @WebParam(mode = WebParam.Mode.OUT, name = "traderAddress", targetNamespace = "urn:ec.europa.eu:taxud:vies:services:checkVat:types")
        javax.xml.ws.Holder<java.lang.String> traderAddress,
        @WebParam(mode = WebParam.Mode.OUT, name = "traderNameMatch", targetNamespace = "urn:ec.europa.eu:taxud:vies:services:checkVat:types")
        javax.xml.ws.Holder<java.lang.String> traderNameMatch,
        @WebParam(mode = WebParam.Mode.OUT, name = "traderCompanyTypeMatch", targetNamespace = "urn:ec.europa.eu:taxud:vies:services:checkVat:types")
        javax.xml.ws.Holder<java.lang.String> traderCompanyTypeMatch,
        @WebParam(mode = WebParam.Mode.OUT, name = "traderStreetMatch", targetNamespace = "urn:ec.europa.eu:taxud:vies:services:checkVat:types")
        javax.xml.ws.Holder<java.lang.String> traderStreetMatch,
        @WebParam(mode = WebParam.Mode.OUT, name = "traderPostcodeMatch", targetNamespace = "urn:ec.europa.eu:taxud:vies:services:checkVat:types")
        javax.xml.ws.Holder<java.lang.String> traderPostcodeMatch,
        @WebParam(mode = WebParam.Mode.OUT, name = "traderCityMatch", targetNamespace = "urn:ec.europa.eu:taxud:vies:services:checkVat:types")
        javax.xml.ws.Holder<java.lang.String> traderCityMatch,
        @WebParam(mode = WebParam.Mode.OUT, name = "requestIdentifier", targetNamespace = "urn:ec.europa.eu:taxud:vies:services:checkVat:types")
        javax.xml.ws.Holder<java.lang.String> requestIdentifier
    );

    @WebMethod
    @RequestWrapper(localName = "checkVat", targetNamespace = "urn:ec.europa.eu:taxud:vies:services:checkVat:types", className = "eu.europa.ec.webapi.CheckVat")
    @ResponseWrapper(localName = "checkVatResponse", targetNamespace = "urn:ec.europa.eu:taxud:vies:services:checkVat:types", className = "eu.europa.ec.webapi.CheckVatResponse")
    public void checkVat(
        @WebParam(mode = WebParam.Mode.INOUT, name = "countryCode", targetNamespace = "urn:ec.europa.eu:taxud:vies:services:checkVat:types")
        javax.xml.ws.Holder<java.lang.String> countryCode,
        @WebParam(mode = WebParam.Mode.INOUT, name = "vatNumber", targetNamespace = "urn:ec.europa.eu:taxud:vies:services:checkVat:types")
        javax.xml.ws.Holder<java.lang.String> vatNumber,
        @WebParam(mode = WebParam.Mode.OUT, name = "requestDate", targetNamespace = "urn:ec.europa.eu:taxud:vies:services:checkVat:types")
        javax.xml.ws.Holder<javax.xml.datatype.XMLGregorianCalendar> requestDate,
        @WebParam(mode = WebParam.Mode.OUT, name = "valid", targetNamespace = "urn:ec.europa.eu:taxud:vies:services:checkVat:types")
        javax.xml.ws.Holder<java.lang.Boolean> valid,
        @WebParam(mode = WebParam.Mode.OUT, name = "name", targetNamespace = "urn:ec.europa.eu:taxud:vies:services:checkVat:types")
        javax.xml.ws.Holder<java.lang.String> name,
        @WebParam(mode = WebParam.Mode.OUT, name = "address", targetNamespace = "urn:ec.europa.eu:taxud:vies:services:checkVat:types")
        javax.xml.ws.Holder<java.lang.String> address
    );
}
