package eu.europa.ec.webapi;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.9
 * 2017-01-17T10:57:01.176+01:00
 * Generated source version: 3.1.9
 * 
 */
@WebServiceClient(name = "checkVatService", 
                  wsdlLocation = "http://ec.europa.eu/taxation_customs/vies/checkVatService.wsdl",
                  targetNamespace = "urn:ec.europa.eu:taxud:vies:services:checkVat") 
public class CheckVatService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("urn:ec.europa.eu:taxud:vies:services:checkVat", "checkVatService");
    public final static QName CheckVatPort = new QName("urn:ec.europa.eu:taxud:vies:services:checkVat", "checkVatPort");
    static {
        URL url = null;
        try {
            url = new URL("http://ec.europa.eu/taxation_customs/vies/checkVatService.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(CheckVatService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://ec.europa.eu/taxation_customs/vies/checkVatService.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public CheckVatService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public CheckVatService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CheckVatService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public CheckVatService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public CheckVatService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public CheckVatService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns CheckVatPortType
     */
    @WebEndpoint(name = "checkVatPort")
    public CheckVatPortType getCheckVatPort() {
        return super.getPort(CheckVatPort, CheckVatPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CheckVatPortType
     */
    @WebEndpoint(name = "checkVatPort")
    public CheckVatPortType getCheckVatPort(WebServiceFeature... features) {
        return super.getPort(CheckVatPort, CheckVatPortType.class, features);
    }

}
